version: '3.9'
services:
  web:
    build: web/.
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:8080"
