version: '3.9'
services:
  web:
    build: web/.
    environment:
      MYSQL_URL: "mysql://root:password@db:3306/hermod"
    depends_on:
      - db
    restart: on-failure
  alb:
    build: alb/.
    ports:
      - "8080:8080"
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: hermod
      MYSQL_USER: hermod
      MYSQL_USER_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /tmp/mysql:/var/lib/mysql
